[build]
  command = "npm run generate"
  publish = ".output/public"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[build.environment]
  NITRO_PRESET = "netlify"